In [1]:
import pandas as pd
# import os
#
# # 改变相对路径
# os.chdir(r'D:\wordspace\ai_22_work_bj\pandasProject\day02')

## 1.Pandas操作CSV文件 和 TSV文件

### 1.1 Pandas读取csv文件数据, 获取df对象

In [2]:
# 1.读取csv->df对象
# 加载所有列
# df = pd.read_csv('./data/stock_day.csv')

# 加载指定列的数据
df = pd.read_csv('../data/stock_day.csv', usecols=['open', 'high', 'close', 'low'])
df

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48
...           ...    ...    ...    ...
2015-03-06  13.17  14.48  14.28  13.13
2015-03-05  12.88  13.45  13.16  12.87
2015-03-04  12.80  12.92  12.90  12.61
2015-03-03  12.52  13.06  12.70  12.52
2015-03-02  12.25  12.67  12.52  12.20

[643 rows x 4 columns]

### 1.2 Pandas写出数据到csv文件中

In [6]:
# 场景1: 写出数据到文件, 包括:行索引,列名,数据
# df.head(10).to_csv('./data/stock_day_head10_01.csv')
# print("写出成功")

# 场景2: 写出数据到文件, 包括:列名, 数据
# df.head(10).to_csv('./data/stock_day_head10_02.csv', index=False)
# print("写出成功")

# 场景3: 写出数据到文件, 包括:数据
df.head(10).to_csv('./data/stock_day_head10_03.csv', index=False, header=False)
print("写出成功")

写出成功

### 1.3 写出数据到tsv文件中

In [9]:
# 1. Pandas写出数据到tsv文件中
# df.head(10).to_csv('./data/stock_day_head10_01.tsv', sep='\t')      # 导出所有列, sep是分隔符, 默认是逗号

# columns:表示把哪些列写到文件中, 默认是:全列
df.head(10).to_csv('./data/stock_day_head10_02.tsv', sep='\t', columns=['open', 'close'])

# mode:表示追加还是覆盖, w->write(覆盖), 默认的          a->append(追加)
# df.head(10).to_csv('./data/stock_day_head10_02.tsv', sep='\t', columns=['open', 'close'], mode='a')
# print("写出成功")

### 1.4 Pandas读取tsv文件, 获取df对象

In [12]:
# 参1:数据源文件的路径
# 参2: sep:分隔符, 默认是逗号, 如果是tsv文件, 要写成'\t'
# 参3: index_col:表示把第0列(第1列)设置为行索引
df = pd.read_csv('./data/stock_day_head10_02.tsv', sep='\t', index_col=0)
df

             open  close
2018-02-27  23.53  24.16
2018-02-26  22.80  23.53
2018-02-23  22.88  22.82
2018-02-22  22.25  22.28
2018-02-14  21.49  21.92
2018-02-13  21.40  21.48
2018-02-12  20.70  21.19
2018-02-09  21.20  20.36
2018-02-08  21.79  21.88
2018-02-07  22.69  21.80